### ISSUE TITLE
「簡報頁」連結

### ISSUE THREAD

**Issue by IanWang1020** [IanWang1020/Webexpo#11]
\<a href="narrative/narrative.html"\>簡報頁\</a\>

連結類似這樣，請加上並測試完整性

**Comment by Maggie-Guo** [comment]
呃什麼是完整性?

**Comment by Maggie-Guo** [comment]
連結已全部加上ˊˇˋ

**Comment by IanWang1020** [comment]
OK

**Comment by IanWang1020** [comment]
有個錯誤，href裡面應該是 "../narrative/narrative.html" 才對，現在這樣會找不到網頁

**Comment by Maggie-Guo** [comment]
哇所以少一個"l"?

**Comment by IanWang1020** [comment]
不是，是前面少了 ../

**Comment by Maggie-Guo** [comment]
前面的../我一開始就有加上了

**Comment by Maggie-Guo** [comment]
喔現在這樣可以連了，
那是因為本來narraitive的資料夾就沒有narraitive.html的檔，
不過應該是我這裡的沒有吧我也不清楚，
總之我加上去之後就可以連了ˊˋ
欸可是我這樣做好像也怪怪的ˊˋ

**Comment by IanWang1020** [comment]
處理好了，有問題的我也搞定了
