### ISSUE TITLE
有關進度報告

### ISSUE THREAD

**Issue by Maggie-Guo** [IanWang1020/Webexpo#19]
為什麼其他頁的程式碼都像這樣:
<div style="background-image:url(pages/21.jpg)"></div>
可是這頁的是這樣?
<div class="hard" style="background-image:url(pages/22.jpg)"></div>
多了一個class="hard"是什麼意思?

**Comment by Maggie-Guo** [comment]
哇程式碼他無法顯示欸，
總之就是有一頁多了一個class="hard"是什麼意思?

**Comment by IanWang1020** [comment]
就是加上封面封底的效果，這個不重要…

**Comment by Maggie-Guo** [comment]
呃什麼效果?所以那個可以刪掉?

**Comment by IanWang1020** [comment]
我已經改好了，妳別動

**Comment by IanWang1020** [comment]
這個也是用FB問一下就好了
